// src/components/molecules/Footer.vue
<template>
  <Container class="footer-container" maxWidth="1200px">
    <footer class="footer">
      <section class="footer__section">
        <h3 class="footer__section__title">Interested in my work?</h3>
        <p class="footer__section__paragraph">
          Did I make you curious about my work? View my complete portfolio and
          follow my work!
        </p>
        <Button
          size="normal"
          variant="primary"
          href="https://www.behance.net/jaschahuisman"
          :icon="['fab', 'behance']"
          newTab
        >
          Visit my portfolio
        </Button>
      </section>
      <section class="footer__section">
        <h3 class="footer__section__title">I'm an open book.</h3>
        <p class="footer__section__paragraph">
          I like to open source most of my projects, so that everyone can learn
          something from my projects.
        </p>
        <Button
          size="normal"
          href="https://www.github.com/jaschahuisman/jaschahuisman"
          :icon="['fab', 'github']"
          newTab
        >
          Check the repo
        </Button>
      </section>
      <section class="footer__section">
        <h3 class="footer__section__title">Let's connect.</h3>
        <p class="footer__section__paragraph">
          Give me a call, or even a text message will work. Then we we'll talk
          about what we can do for each other.
        </p>
        <div class="footer__section__icons">
          <a
            v-for="icon in icons"
            class="footer__section__icons__icon"
            target="_blank"
            rel="noopener noreferrer"
            :key="icon.id"
            :href="icon.href"
            :title="icon.title"
          >
            <icon :icon="icon.icon" :color="icon.color" />
          </a>
        </div>
      </section>
    </footer>
  </Container>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Button from "@/components/atoms/Button.vue";
import Container from "@/components/wrappers/Container.vue";

export default defineComponent({
  name: "Footer",
  components: {
    Button,
    Container,
  },
  data() {
    return {
      icons: [
        {
          id: "linkedin",
          href: "https://www.linkedin.com/in/jaschahuisman",
          icon: ["fab", "linkedin-in"],
          color: "#2867B2",
          title: "LinkedIn",
        },
        {
          id: "whatsapp",
          href: "https://wa.me/+31611808827?text=Hi%20Jascha!&lang=en",
          icon: ["fab", "whatsapp"],
          color: "#25D366",
          title: "Whatsapp",
        },
        {
          id: "instagram",
          href: "https://www.instagram.com/jaschahuisman",
          icon: ["fab", "instagram"],
          color: "#E1306C",
          title: "Instagram",
        },
        {
          id: "github",
          href: "https://www.github.com/jaschahuisman",
          icon: ["fab", "github"],
          title: "Github",
        },
      ],
    };
  },
});
</script>

<style lang="sass" scoped>
@import "@/styles/_media.scss"
.footer
  display: grid
  grid-template-columns: repeat(3, 1fr)
  grid-gap: 2rem
  margin-top: 2rem
  margin-bottom: 4rem
  @include media("<=1200px", ">phone")
    padding: 0 1.5rem
  @include media("<=tablet", ">phone")
    grid-template-columns: repeat(1, 1fr)
    grid-gap: 4rem
  @include media("<=400px")
    grid-template-columns: repeat(1, 1fr)
    justify-content: center
    text-align: center
  &__section
    display: flex
    flex-direction: column
    &__title
      margin-bottom: 0.5rem
    &__paragraph:not(:last-child)
      margin-bottom: 2.5rem
    &__icons
      display: flex
      align-items: center
      @include media("<=400px")
        justify-content: center
      &__icon
        width: 1.5rem
        height: 1.5rem
        margin-right: 1rem
        svg
          width: 100%
          height: 100%
</style>

// src/components/sections/Footer/index.tsx
import React from 'react';
import { animateScroll } from 'react-scroll';
import Container from '../../wrappers/Container';
import Section from '../../wrappers/Section';
import { FaGithub, FaLinkedin, FaWhatsapp, FaInstagram, FaBehance } from 'react-icons/fa';
import Button from '../../atoms/Button';

const Footer: React.FC = () => {
	const scrollToTop = () => {
		animateScroll.scrollToTop();
	};

	return (
		<Section animateIn={false}>
			<footer className='footer'>
				<Container maxWidth='1200px'>
					<div onClick={scrollToTop} className='footer__scrolltop'>
						Scroll back to the top <span className='material-icons-outlined'>arrow_circle_up</span>
					</div>
					<div className='footer__sections' role='list'>
						<div className='footer__section' role='listitem'>
							<h2 className='footer__section__title'>Interested in my work?</h2>
							<p>Did I make you curious about my work? View my complete portfolio and follow my work!</p>
							<Button
								size='small'
								variant='primary'
								icon={<FaBehance />}
								href='https://www.behance.net/jaschahuisman'
								target='_blank'
								rel='noopener noreferrer'
								title='Behance portfolio'
							>
								My portfolio
							</Button>
						</div>
						<div className='footer__section' role='listitem'>
							<h2 className='footer__section__title'>I&apos;m an open book.</h2>
							<p>
								I like to open source most of my projects, so that everyone can learn something from my projects.
							</p>
							<Button
								size='small'
								icon={<FaGithub />}
								href='https://www.github.com/jaschahuisman/jaschahuisman'
								target='_blank'
								rel='noopener noreferrer'
								title='GitHub repository'
							>
								View repository
							</Button>
						</div>
						<div className='footer__section' role='listitem'>
							<h2 className='footer__section__title'>Let&apos;s connect.</h2>
							<p>
								Give me a call, or even a text message will work. Then we we&apos;ll talk about what we can do for
								each other.
							</p>
							<ul className='footer__section__social-icons'>
								<li className='footer__section__social-icons__icon'>
									<a
										href='https://www.linkedin.com/in/jaschahuisman/'
										target='_blank'
										rel='noopener noreferrer'
										aria-label='LinkedIn'
										role='link'
									>
										<FaLinkedin fill='#2867B2' />
									</a>
								</li>
								<li className='footer__section__social-icons__icon'>
									<a
										href='https://wa.me/+31611808827?text=Hi%20Jascha!&lang=en'
										target='_blank'
										rel='noopener noreferrer'
										aria-label='WhatsApp'
										role='link'
									>
										<FaWhatsapp fill='#4AC959' />
									</a>
								</li>
								<li className='footer__section__social-icons__icon'>
									<a
										href='https://www.instagram.com/jaschahuisman'
										target='_blank'
										rel='noopener noreferrer'
										aria-label='Instagram'
										role='link'
									>
										<FaInstagram fill='#E1306C' />
									</a>
								</li>
								<li className='footer__section__social-icons__icon'>
									<a
										href='https://www.github.com/jaschahuisman'
										target='_blank'
										rel='noopener noreferrer'
										aria-label='GitHub'
										role='link'
									>
										<FaGithub />
									</a>
								</li>
							</ul>
						</div>
					</div>
				</Container>
			</footer>
		</Section>
	);
};

export default Footer;
