// src/components/pages/home/index.tsx
import React from 'react';
import Helmet from 'react-helmet';
import HeaderSection from '../../sections/Header';
import ExcerptSection from '../../sections/Excerpt';
import AboutSection from '../../sections/About';
import TimelineSection from '../../sections/Timeline';
import ContactSection from '../../sections/Contact';
// import ProjectsSection from '../../sections/Projects';
import PortraitImg from '../../../assets/img/jascha-portrait.jpeg';

const HomePage: React.FC = () => {
	return (
		<React.Fragment>
			<Helmet>
				<meta property='og:image' content={`http://www.jaschahuisman.nl${PortraitImg}`} />
			</Helmet>
			<HeaderSection />
			<ExcerptSection />
			<AboutSection />
			{/* <ProjectsSection /> */}
			<TimelineSection />
			<ContactSection />
		</React.Fragment>
	);
};

export default HomePage;

// src/components/pages/Home.vue
<script setup lang="ts">
import HeaderSection from "@/components/sections/home/HeaderSection.vue";
import ExcerptSection from "@/components/sections/home/ExcerptSection.vue";
import AboutSection from "@/components/sections/home/AboutSection.vue";
import TimelineSection from "@/components/sections/home/TimelineSection.vue";
import ContactSection from "@/components/sections/home/ContactSection.vue";
</script>

<template>
  <main id="home" class="homepage">
    <header-section />
    <excerpt-section />
    <about-section />
    <timeline-section />
    <contact-section />
  </main>
</template>
